version: '3.7'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.5.1'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es01
    ports:
      - 9200:9200
