version: '3.7'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.1'
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
