version: '3.7'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    build: ./docker/elasticsearch
    ports:
      - 9200:9200
