version: '3.7'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'always'
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    volumes:
      - ./search-api/:/go/src/app
  elasticsearch:
    container_name: 'elasticsearch'
    build: ./docker/elasticsearch
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
    driver: local
